language: go
go:
- 1.11.x

sudo: required

install:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    go get github.com/Masterminds/glide &&
    glide install;
  fi

script:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    curl -sL https://git.io/goreleaser | bash;
  fi
  
notifications:
  email: false
